"""order date

Revision ID: 555b6caa6dba
Revises: 9fca3dbc6078
Create Date: 2023-06-10 18:35:52.944777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555b6caa6dba'
down_revision = '9fca3dbc6078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
