"""user address

Revision ID: 858624a001fa
Revises: 1e2a7fd0a07e
Create Date: 2023-06-10 14:10:19.206567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858624a001fa'
down_revision = '1e2a7fd0a07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('streetnumber', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('zipecode', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
        batch_op.alter_column('country',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('firstname',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.drop_column('city')
        batch_op.drop_column('zipecode')
        batch_op.drop_column('streetnumber')
        batch_op.drop_column('street')

    # ### end Alembic commands ###
